movieproject/movieapp/urls.py
from django.urls import path
from .import views
app_name='movieapp'
urlpatterns = [
    #path('',views.index,name='index'),
    path('',views.MovieList.as_view(),name="index"),

    #path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('movie/<int:pk>',views.MovieDetail.as_view(),name="detail"),

    #path('add/',views.add_movie,name='add_movie'),
    path('add/',views.Movieadd.as_view(), name="add_movie"),

    #path('update/<int:id>/',views.update,name='update'),
    path('update/<int:pk>/',views.Movieupdate.as_view(), name="update"),

   # path('delete/<int:id>/', views.delete, name='delete'),
    path('delete/<int:pk>/',views.Moviedelete.as_view(), name="delete"),
]

movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/',admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.CharField(max_length=250)
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery',null=True,blank=True)


    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy


#def index(request):
#   movie = Movie.objects.all()
#   context = {
#       'movie_list': movie
#   }
#   return render(request, "index.html", context)

class MovieList(ListView):
    model=Movie
    template_name="index.html"
    context_object_name = "movie_list"


#def detail(request, movie_id):
 #   movie=Movie.objects.get(id=movie_id)
  #  return render(request,"detail.html",{'movie':movie})

class MovieDetail(DetailView):
    model=Movie
    template_name='detail.html'
    context_object_name="movie_detail"



#def add_movie(request):
 #   if request.method=='POST':
  #      name=request.POST.get('name')
   #     desc=request.POST.get('desc')
    #    year=request.POST.get('year')
     #   img = request.FILES['img']
      #  movie=Movie(name=name,desc=desc,year=year,img=img)
       # movie.save()
        #return redirect("/")
    #return render(request,'add.html')

class Movieadd(CreateView):
    model=Movie
    template_name="add.html"
    fields='__all__'
    success_url=reverse_lazy('movieapp:index')

 
#def update(request,id):
 #   movie=Movie.objects.get(id=id)
  #  form=MovieForm(instance=movie)
   ## if(request.method=="POST"):
     #   form = MovieForm(request.POST,request.FILES,instance=movie)
      #  if form.is_valid():
       #     form.save()
        #    return redirect('/')
    #return render(request,'edit.html',{'form':form})

class Movieupdate(UpdateView):
    model=Movie
    template_name="add.html"
    fields='__all__'
    success_url = reverse_lazy('movieapp:index')


#def delete(request,id):
 #   if request.method=='POST':
  #      movie=Movie.objects.get(id=id)
   #     movie.delete()
    #    return redirect('/')
    #return render(request,'delete.html')

class Moviedelete(DeleteView):
    model=Movie
    template_name="delete.html"
    fields='__all__'
    success_url = reverse_lazy('movieapp:index')

movieproject/templates/add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <!--input type="text" name="name" placeholder="Enter your movie name">
    <input type="text" name="desc" placeholder="Enter the movie description">
    <input type="text" name="year" placeholder="Enter your movie year">
    <input type="file" name="img"-->
    <table>
       {{form.as_table}}
        <!--{{form|crispy}}-->
    </table>

    <input type="submit">

</form>



{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="'stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
  <a class="btn btn-success" href="{% url 'movieapp:add_movie' %}" style="align:center;">ADD MOVIE</a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movieproject/templates/delete.html
{% load static %}
{% block body %}

<form method="POST">
      {% csrf_token %}
      <p> Are you sure you want to delete???</p>
      <input type="submit">
</form>

{% endblock %}

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="comtainer">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="350">
        </div>
<div class="col-md-6">
    <h4>{{movie.name}}</h4>
    <h6>{{movie.desc}}</h6>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
</div>
    </div>
</div>

{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
      <div class="col-md-3">
          <div class="card" style="margin-right:10px; margin-top:10px; ">
            <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250px;">
            <div class="card-body"  >
                <h5 class="card-title" style="height:50px;" >{{i.name}}</h5>
                <p class="card-text" style="height:70px;">{{i.desc}}</p>
                <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
            </div>
          </div>
      </div>
        {% endfor %}

    </div>
</div>
{% endblock %}